# Generated by Django 4.0.6 on 2022-07-22 16:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ingredients", models.TextField()),
                ("how_to_cook", models.TextField()),
                ("time", models.IntegerField()),
                ("recipe_yield", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
