# Generated by Django 4.0.6 on 2022-07-28 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0004_recipe_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="person",
        ),
        migrations.AddField(
            model_name="recipe",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
