# Generated by Django 4.0.6 on 2022-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="cellphone",
            field=models.CharField(default="", max_length=11),
        ),
    ]
