# Generated by Django 4.0.6 on 2022-08-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_student_cellphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
