# Generated by Django 4.0.6 on 2022-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="domestic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="name",
            field=models.CharField(default="N/A", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="poisonous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="predator",
            field=models.BooleanField(default=False),
        ),
    ]
