# Generated by Django 4.0.6 on 2022-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_day", models.DateField()),
                ("return_day", models.DateField()),
                ("query_date", models.DateField()),
                ("extra_info", models.TextField(blank=True, max_length=200)),
                (
                    "trip_class",
                    models.CharField(
                        choices=[
                            ("ECON", "Econômica"),
                            ("EXEC", "Executiva"),
                            ("PRIC", "Primeira Classe"),
                        ],
                        default=0,
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
