# Generated by Django 4.0.6 on 2022-08-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("M", "Movie"), ("S", "Series")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("release_date", models.DateField()),
                ("likes", models.PositiveIntegerField(default=0)),
                ("dislikes", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
